name: Deploy HTML ke GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload ke GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      - name: Deploy ke GitHub Pages
        uses: actions/deploy-pages@v2
