name: Deploy HTML ke GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload ke GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy ke GitHub Pages
        uses: actions/deploy-pages@v4
